<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Adskii_Rasgon" failures="0" tests="5" name="Default test" time="0.057" errors="0" timestamp="2024-10-20T19:18:43 UZT">
  <testcase classname="test.java.lesson14_testng.FactorialTest" name="testFactorial" time="0.009"/>
  <testcase classname="test.java.lesson14_testng.FactorialTest" name="testFactorial" time="0.001"/>
  <testcase classname="test.java.lesson14_testng.FactorialTest" name="testFactorial" time="0.001"/>
  <testcase classname="test.java.lesson14_testng.FactorialTest" name="testFactorial" time="0.001"/>
  <testcase classname="test.java.lesson14_testng.FactorialTest" name="testFactorialThrowsExceptionForNegativeNumber" time="0.001"/>
</testsuite> <!-- Default test -->
